### ISSUE TITLE
show modifier class name

### ISSUE THREAD

**Issue by benaveryee** [hmrc/component-library-template#13]
When a modifier class is used with a markup section, the component library page should show the class name along with the description. currently, only the description is shown, and it is up to the author to name the class in the description too.

e.g. 
.underlined - The text will be underlined.

currently will only display 'The text will be underlined', which makes the reader have to look at the markup to see which class is the modifier.

it would be clearer if the full line is shown, i.e. '.underlined - The text will be underlined.'

**Comment by feedmypixel** [comment]
currently this is up to the author. http://hmrc.github.io/assets-frontend/section-buttons.html for example. But I like the idea of automating this.

:100: :8ball: :tiger:

**Comment by feedmypixel** [comment]
Added in commit: https://github.com/hmrc/component-library-template/commit/2ffb21bca4b37876c2053717689a9e69879465ea
