### ISSUE TITLE
Make elements in modifiers unique via a handlebars helper

### ISSUE THREAD

**Issue by feedmypixel** [hmrc/component-library-template#15]
In the instance of the [errors](http://hmrc.github.io/assets-frontend/section-errors.html) section we have multiple modifiers using markup that includes a `label` with an `input`. Due to the `for` attribute on the `label` pointing to the `id` on the `input` all `inputs` on the page point to the initial `label` in the markup example.

It would be handy to provide a count which could be appended to the `label` for attribute and the `input` id so each `label` refers to the correct `input`

```
id="id_name_{{count}}"
```

**Comment by rpowis** [comment]
You don't need the `for` attribute on the label if it's wrapping the `input`...

https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly

**Comment by feedmypixel** [comment]
good point - thats an easy fix :+1:
