### ISSUE TITLE
Large images need max width set...

### ISSUE THREAD

**Issue by ian-leggett** [hmrc/component-library-template#64]
If you add a large image into the README.md files in the Design system the width isn't contained. We need to contain the width inside the example `div`.
<img width="1398" alt="screen shot 2018-06-01 at 15 40 33" src="https://user-images.githubusercontent.com/10154302/40846666-29a6a740-65b2-11e8-9ff9-65abfe8f6143.png">

**Comment by gordonmcmullan** [comment]
Fixed by PR #65
